---
title: "3-3. try-catch"
date: 2023-06-04
---
#### 1. 语法结构
```java
try{
    //可能出现异常的代码    
}catch(异常类型1 变量名1){
     //当产生异常类型1时的处理措施
}catch(异常类型2 变量名2){
     //当产生异常类型2时的处理措施
}catch(异常类型3 变量名3){
     //当产生异常类型3时的处理措施
}
  ....
finally{
     //无论是否发生异常，都无条件执行的语句
}
```
- try：捕获异常的第一步是用try{…}语句块选定捕获异常的范围，将可能出现异常的代码放在try语句块中。
- catch：在catch语句块中是对异常对象进行处理的代码。每个try语句块可以伴随一个或多个catch语句，用于处理可能产生的不同类型的异常对象。

#### 2. 异常类型的选择
如果明确知道产生的是何种异常，可以用该异常类作为catch的参数；也可
以用其父类作为catch的参数。比 如 ： 可以用ArithmeticException 类作为参数的地方，就可以用
RuntimeException类作为参数，或者用所有异常的父类Exception类作为参数。

但不能是与ArithmeticException类无关的异常，如NullPointerException（catch
中的语句将不会执行）。

#### 3. try-catch示例
```java
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
public class ExceptionTest{
    public void test1(){
        String str = "abc"; //非数字字符串
        try{
           int num = Integer.parseInt(str); //非数字字符串转不了
           System.out.println("shit,这里出问题了"); 
        }catch(NumberFormatException e){ //尝试捕获数值类型异常
            System.out.println("YES,捕获到了数值异常");
            System.out.pintln(e.getMessage());//获取异常信息
            e.printStackTrace();//打印详细异常：堆栈追踪
        }catch(NullPointerException e){ //尝试捕获空指针异常
            System.out.println("YES,捕获到了空指针异常");
        }catch(Exception e){ //尝试捕获异常
            System.out.println("这里出现了异常，类型不明");
        }
        System.out.println(num);//无法获取num，num是try里面的局部变量
        System.out.println("后续代码继续执行");
    }
}
```

#### 4. try-catch使用说明
- finally是可选的。
- 使用try将可能出现异常代码包装起来，在执行过程中，一旦出现异常，就会生成一个对应异常类的对象，根据此对象的类型，去catch中进行匹配
- 一旦try中的异常对象匹配到某一个catch时，就进入catch中进行异常的处理。一旦处理完成，就跳出当前的try-catch结构（在没有写finally的情况）。继续执行其后的代码（不会再执行其他catch了，只捕获一次）。

#### 5. 捕获异常的有关信息
捕获异常后，会获取异常对象，对于异常对象e，可以调用下面两个方法，处理（查看）异常信息。

![3-3-1](/img/java/javase/3-3-1.jpg)

- getMessage：获取异常信息，返回字符串
- printStackTrace：打印详细异常：堆栈追踪。获取异常类名和异常信息，以及异常出现在程序中的位置。返回值void。

#### 6. finally的使用
finally是可选的；finally中声明的是一定会被执行的代码。即使catch中又出现异常了，try中有return语句，catch中有return语句，代码没有异常等。finally语句为异常处理提供一个统一的出口，使得在控制流转到程序的其它部分以前，能够对程序的状态作统一的管理。

使用场景：像数据库连接、输入输出流、网络编程Socket等资源，JVM是不能自动的回收的，我们需要自己手动的进行资源的释放。此时的资源释放，就需要声明在finally中。即无论如何资源都会被释放。

##### 6.1 示例1：finally一定会被执行
- 若无异常，执行结果为：finally 1
- 若有异常，执行结果为：finally 2
- 若finally中有return 3，执行结果为：finally 3
总结：finally中的代码总会执行，且会在return之前执行。
```java
public int method(){
    try{
        int[] arr = new int[10];
        System.out.println(arr[10]);//角标越位异常
        return 1;
    }catch(ArrayIndexOutOfBoundsException e){
        e.printStrackTrace();
        return 2;
    }finally{
        System.out.println("finally");
        //return 3;
    }
}
```

##### 6.2 示例2：资源的释放
```java
  public void test2(){
    FileInputStream fis = null; //初始化资源
    try {
      File file = new File("hello1.txt"); 
      fis = new FileInputStream(file);//读取资源,可能读取失败
      
      int data = fis.read(); //开始读取
      while(data != -1){
        System.out.print((char)data);
        data = fis.read();
      }
    } catch (FileNotFoundException e) { //异常：文件打开失败
      e.printStackTrace();
    } catch (IOException e) { //异常：文件传输失败
      e.printStackTrace();
    }finally{
      try { //finally里吗也可能有异常，所以要嵌套一个try...catch
        if(fis != null)//先判断资源是否打开
          fis.close(); //在finally里面关闭资源
      } catch (IOException e) {
        e.printStackTrace();
      }
    }
  }
```

#### 7. 异常的嵌套
try-catch-finally结构可以嵌套。

catch和finally里面也可能会有异常。

#### 8. 注意事项
- catch捕获的顺序：catch中的异常类型如果没有子父类关系，则谁声明在上，谁声明在下无所谓。 catch中的异常类型如果满足子父类关系，则要求子类一定声明在父类的上面。否则，报错
- 变量的范围：在try结构中声明的变量，在出了try结构以后，就不能再被调用

#### 9. 编译时异常和运行时异常的不同处理
- 编译时异常：进行try...catch处理；将其延后成运行时异常
    - 使用try-catch-finally处理编译时异常，使得程序在编译时就不再报错，但是运行时仍可能报错。相当于我们使用try-catch-finally将一个编译时可能出现的异常，延迟到运行时出现。针对于编译时异常，一定要考虑异常的处理。
- 运行时异常：处理没有意义，不用try...catch进行处理。：
    - 开发中，由于运行时异常比较常见，所以我们通常就不针对运行时异常编写try-catch-finally了。

